spring:
  application:
    name: CLOUD-GATEWAY
  cloud:    gateway:      routes:      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:        - Path=/orders**
        filters:
          - name: CircuitBreaker
            args:              name: order-service
              fallbackuri: forward:/fallback/orders
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payments**, /payments/**
        filters:
          - name: CircuitBreaker
            args:
              name: payment-service
              fallbackuri: forward:/fallback/payments
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
server:  port: 8989
  
logging:
  file:
    name: C:\Users\Chandan_Kumar\.MyLogs\microservices-example\gateway\gateway-service.log