server:
  port: 7000

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true  h2:    console:      enabled: true
  application:
    name: ORDER-SERVICE
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

    
logging:
  file:
    name: C:\Users\Chandan_Kumar\.MyLogs\microservices-example\orders\order-service.log